### PR TITLE
feat(formatter): add goimports, gofumpt, jq

### PR DESCRIPTION
**Pull request by jinzhongjia**
goimports

### CODE REVIEW

**Comment by barrett-ruth** [comment]
@nvimdev/core this warrants a discussion about what tools we want to support and what is "bloat." This will also eventually happen to linters once we add enough. Where to draw the line? Because if we accept prs adding tools like this which will always continue to come there isn't a reason to just add a bunch more.

**Comment by jinzhongjia** [comment]
These configurations are just a file, and these configurations can be overwritten at any time, I think there is no problem

**Comment by barrett-ruth** [comment]
> These configurations are just a file, and these configurations can be overwritten at any time, I think there is no problem

I also think they are ok. But @glepnir seems to want to limit number of formatters, not entirely sure tho. Ther are just a few pre-configured tables - wouldnt't consider them bloat imo.

**Comment by jinzhongjia** [comment]
Instead of pr, a discussion area related to preconfiguration can be provided

**Comment by jinzhongjia** [comment]
> Instead of pr, a discussion area related to preconfiguration can be provided

But it's up to @glepnir's decision

**Comment by glepnir** [comment]
see #61

**Pull request merged**
