### PR TITLE
ref: guard.api

### PR DESCRIPTION
**Pull request by xiaoshihou514**
Nothing works yet, just for progress update

_should_ make #68, #76, #86, #109 possible, unless anyone is against this approach

### CODE REVIEW

**Comment by xiaoshihou514** [comment]
spec is in ADVANCED.md!

**Comment by barrett-ruth** [comment]
@xiaoshihou514 status?

**Comment by xiaoshihou514** [comment]
> @xiaoshihou514 status?

Haven't worked on a codebase of this complexity before :crying_face: , still tinkering to find the right abstraction and stuff.

**Comment by xiaoshihou514** [comment]
@glepnir promised a re-factor so closing :+1:

**Pull request closed without merging**
