### PR TITLE
change diff update to whole buffer

### PR DESCRIPTION
**Pull request by glepnir**
diff update has bug .back to update whole buffer

### CODE REVIEW

**Comment by xiaoshihou514** [comment]
> Eliminate update bugs caused by calculating the buffer area

Could you explain this part?🤔

**Comment by glepnir** [comment]
nope. just a try. diff update has bug. now back to update whole buffer if has result .

**Comment by xiaoshihou514** [comment]
Any idea why🤔?

**Comment by glepnir** [comment]
diff return data like `240, 0, 241, 1` of `start_a, start_a, start_b, count_b` Didn't understand the rules. Causes buffer confusion after update.  So first go back and update the entire buffer. I think a benchmark is needed here. Because we need to know whether using diff is worth it. The time to update the entire buffer and the time to run the diff algorithm. It should be possible to benchmark large files

**Comment by glepnir** [comment]
not sure. I remember this code will cause a format bug. 

```lua
local t = {}

function t.a()
end

function t.b()
end

return t
```

**Comment by xiaoshihou514** [comment]
Some limited benchmarking:
https://github.com/xiaoshihou514/guard-bench
Tested by manually toggling update methods and `nvim -u init.lua`

- All files have the spaces changed to 8 spaces, in this case diffing is about 25% percent slower on average
(diff 8ms, no diff 6ms with big.js)

- All files have " = " changed to "=", in this case diffing does better, but still does worse than not diffing
(diff 7ms, no diff 6ms with big.js)

Someone may be interested to do more rigorous and automated benchmarking to find the overall balance, but at this point I think there is really no point perfing the update method. `big.js` is 10k LOC, which is about what you can get when writing serious code, but updating buffer only takes less than 10ms, which I argue is pretty insignificant compared to the heavy lifting done by the formatter itself. Whether or not the file is big, diffing or not does not really change the user experience in terms of formatting speed, it is mostly determined by the formatter itself. And if diffing the buffer contents causes bug from time to time, I would vote for removing it.

**Comment by xiaoshihou514** [comment]
@glepnir mergable yet?

**Comment by xiaoshihou514** [comment]
@glepnir mergable yet?

**Pull request merged**
