### PR TITLE
chore: add luarocks workflow

### PR DESCRIPTION
**Pull request by xiaoshihou514**
Experimental release on luarocks, need to add two github secrets `LUAROCKS_API_KEY` and `MY_RELEASE_PLEASE_TOKEN` (a personal access token)
ref: https://github.com/nvim-neorocks/luarocks-tag-release
@glepnir

### CODE REVIEW

**Comment by xiaoshihou514** [comment]
The workflow would generate a release pr every time one pushes a commit with conventioanl commit messages. And on merging the pr, it would push the release to luarocks

**Comment by glepnir** [comment]
nice work.

**Comment by xiaoshihou514** [comment]
😄 It _should_ work immediately after you added the secrets and merged this pr. I have tested it a bit with [my little plugin](https://github.com/xiaoshihou514/squirrel.nvim)

**Comment by xiaoshihou514** [comment]
@glepnir would you mind merging this after you added the keys?

**Comment by xiaoshihou514** [comment]
Oops

**Pull request closed without merging**
