### PR TITLE
feat: add is formatting

### PR DESCRIPTION
**Pull request by otavioschwanck**
add is_formatting

Useful for statusline

### CODE REVIEW

**Comment by glepnir** [comment]
this need use like `CursorHold` or `CursorMoved` to render statusline after do format ?

**Comment by glepnir** [comment]
so then how you get this function result twice in stl if there no event for trigger render stl .

**Comment by glepnir** [comment]
maybe there need create a `User GuardFormat` event

**Comment by otavioschwanck** [comment]
> so then how you get this function result twice in stl if there no event for trigger render stl .

No idea hahah

image

image

**Comment by otavioschwanck** [comment]
> okay is `CursorHold` when you hold cursor after `updatetime` value it will render stl

there is something missing in this PR ? @glepnir

**Comment by otavioschwanck** [comment]
> I am thinking about create `User GuardFormat` event then you can use in stl

Should have two autocmd, `User GuardFormatStart` `User GuardFormatFinished`

**Comment by glepnir** [comment]
just once and get value from `callback` params like

```lua
nvim_exec_autocmds('User', {pattern = 'GuardFormat', modeline =true, data = { fmt_status = 'Pending' or 'Done'}

**Comment by otavioschwanck** [comment]
> just one is enough and get value from `callback` params like
> 
> ```lua
> nvim_exec_autocmds('User', {pattern = 'GuardFormat', modeline =true, data = { fmt_status = 'Pending' or 'Done'}
> ```

you are right!

**Comment by glepnir** [comment]
#62

**Pull request closed without merging**
